# Generated by Django 4.2.2 on 2023-06-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('WFP', 'Oczekiwanie na płatność'), ('C', 'Anulowana'), ('UP', 'Nieopłacona'), ('P', 'Opłacona'), ('R', 'Zwrócona')], default='WFP', max_length=10),
        ),
    ]
