# Generated by Django 4.2 on 2023-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Decent'), (3, 'Ok'), (4, 'Great'), (5, 'Awesome')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Paypal', 'Paypal'), ('PayU', 'Payu'), ('BLIK', 'Blik'), ('Credit card', 'Credit Card'), ('Traditional transfer', 'Traditional Transfer')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Waiting for payment', 'Waiting For Payment'), ('In progress', 'In Progress'), ('Canceled', 'Canceled'), ('Approved', 'Approved')], default='Waiting for payment', max_length=25),
        ),
    ]
